#!/usr/bin/env python3
# -*- coding=utf-8 -*-
# 本脚由亁颐堂现任明教教主编写，用于乾颐盾Python课程！
# 教主QQ:605658506
# 亁颐堂官网www.qytang.com
# 教主技术进化论拓展你的技术新边疆
# https://ke.qq.com/course/271956?tuin=24199d8a
import sqlite3
import os


def netflowdb(netflow_dict):
    if os.path.exists('netflow.sqlite'):
        os.remove('netflow.sqlite')

    # 连接SQLite数据库
    conn = sqlite3.connect('netflow.sqlite')
    cursor = conn.cursor()

    # 执行创建表的任务
    cursor.execute("create table netflowdb (源地址 varchar(40), 目的地址 varchar(40), 协议 int, 源端口 int, 目的端口 int, 入接口ID int, 入向字节数 int)")

    # 读取Python字典数据，并逐条写入SQLite数据库
    cursor.execute("insert into netflowdb values ('%s', '%s', %d, %d, %d, %d, %d)" % (netflow_dict['IPV4_SRC_ADDR'],
                                                                                              netflow_dict['IPV4_DST_ADDR'],
                                                                                              netflow_dict['PROTOCOL'],
                                                                                              netflow_dict['L4_SRC_PORT'],
                                                                                              netflow_dict['L4_DST_PORT'],
                                                                                              netflow_dict['INPUT_INTERFACE_ID'],
                                                                                              netflow_dict['IN_BYTES']))

    # 读取整个qytang_teachers_info表的信息，并且打印
    cursor.execute("select * from netflowdb")
    yourresults = cursor.fetchall()

    for netflowinfo in yourresults:
        print(netflowinfo)

    conn.commit()


if __name__ == "__main__":
    # Python字典对象，我们将把它写入SQLite数据库
    netflow_dict = {'IPV4_SRC_ADDR': '10.1.1.252',
                    'IPV4_DST_ADDR': '10.1.1.253',
                    'PROTOCOL': 6,
                    'L4_SRC_PORT': 24038,
                    'L4_DST_PORT': 22,
                    'INPUT_INTERFACE_ID': 1,
                    'IN_BYTES': 2608}
    writedb(netflow_dict)